// Code generated by goctl. DO NOT EDIT.
package domain

import (
	"mime/multipart"
)

type StateKV struct {
	Key int64   `json:"key"`
	Val float64 `json:"val"`
}

type MonitorStateReq struct {
	Type      string `json:"type,omitempty"`
	StartTime int64  `json:"start_time,omitempty"`
	EndTime   int64  `json:"end_time,omitempty"`
}

type MonitorStateResp struct {
	Data []*StateKV `json:"data"`
}

type MonitorInfoResp struct {
	CPUState     []*StateKV `json:"cpu_state"`
	MemoryState  []*StateKV `json:"memory_state"`
	DiskState    []*StateKV `json:"disk_state"`
	NetSendState []*StateKV `json:"net_send_state"`
	NetRecvState []*StateKV `json:"net_recv_state"`
}

type MonitorConfigReq struct {
	IsStart      bool    `json:"is_start"`
	CpuLimit     float64 `json:"cpu_limit"`
	DiskLimit    float64 `json:"disk_limit"`
	MenLimit     float64 `json:"men_limit"`
	NetSendLimit float64 `json:"net_send_limit"`
	NetRecvLimit float64 `json:"net_recv_limit"`
	NotifyType   int     `json:"notify_type"`
	Email        string  `json:"email"`
}

type MonitorConfigResp struct {
	Id           int64   `json:"id"`
	IsStart      bool    `json:"is_start"`
	CpuLimit     float64 `json:"cpu_limit"`
	DiskLimit    float64 `json:"disk_limit"`
	MenLimit     float64 `json:"men_limit"`
	NetSendLimit float64 `json:"net_send_limit"`
	NetRecvLimit float64 `json:"net_recv_limit"`
	NotifyType   int     `json:"notify_type"`
	Email        string  `json:""email"`
}

type User struct {
	Id       int    `json:"id;primary_key"`
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Status   int64  `json:"status"`
	IsSystem int64  `json:"is_system"`
	CreateAt int64  `json:"create_at"`
	UpdateAt int64  `json:"update_at"`
	DeleteAt int64  `json:"delete_at"`
}

type File struct {
	Filename string `json:"filename"`
	Path     string `json:"path"` // 业务相对路径
	Mtime    int64  `json:"mtime"`
	Size     int64  `json:"size"`
	IsDir    bool   `json:"is_dir"`
	SHA256   string `json:"sha256,omitempty"`
}

type IdReq struct {
	Id int `json:"id" from:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string `json:"token"`
	Id       int    `json:"id"`
	Name     string `json:"name"`
	Status   int64  `json:"status"`
	IsSystem int64  `json:"is_system"`
}

type RegisterReq struct {
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Password2 string `json:"password2"`
}

type RegisterResp struct {
	Token  string `json:"token"`
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Status int    `json:"status"`
}

type UserListReq struct {
	Ids   []int  `json:"ids,omitempty" query:"ids"`
	Name  string `json:"name,omitempty" query:"name"`
	Page  int    `json:"page,omitempty" query:"page"`
	Count int    `json:"count,omitempty" query:"count"`
}

type UserListResp struct {
	Count int64 `json:"count"`
	List  []*User
}

type UpPasswordReq struct {
	Id     int    `json:"id"`
	OldPwd string `json:"oldPwd"`
	NewPwd string `json:"newPwd"`
}

type FilePathReq struct {
	Path string `json:"path" form:"path"`
}

type FileListResp struct {
	List []*File `json:"list"`
}

type FileDeleteReq struct {
	Path      string `json:"path" form:"path"`
	Recursive bool   `json:"recursive"`
}

type UploadFileReq struct {
	Path           string `json:"path" form:"path"`
	File           multipart.File
	Header         *multipart.FileHeader
	ExpectedSHA256 string `form:"sha256,omitempty"`
}

type UploadFileResp struct {
}

type FileSearchReq struct {
	Keyword  string `json:"keyword" form:"keyword"` // 搜索关键词
	Prefix   bool   `json:"prefix" form:"prefix"`   // 是否前缀匹配
	OnlyFile bool   `json:"only_file,omitempty" form:"only_file"`
	OnlyDir  bool   `json:"only_dir,omitempty" form:"only_dir"`
	Limit    int    `json:"limit,omitempty" form:"limit"`
}

type FileSearchResp struct {
	Total int           `json:"total"`
	List  []FileSummary `json:"list"`
}

type FileSummary struct {
	Path  string `json:"path" form:"path"`
	Name  string `json:"name"`
	IsDir bool   `json:"is_dir"`
}
